name:                KolyaBot
version:             0.1.0.0
github:              "papagvas/KolyaBot"
license:             BSD3
author:              "Matthew Gvasalia"
maintainer:          "papagvasexy@gmail.com"
copyright:           "2023 Matthew Gvasalia"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/papagvas/KolyaBot#readme>

dependencies:
- base
- di
- generic-lens
- lens
- polysemy
- text
- text-show
- calamity
- di-polysemy
- data-default
- data-flags
- polysemy-plugin

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Polysemy.Plugin

library:
  source-dirs: src

executables:
  KolyaBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KolyaBot

tests:
  KolyaBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KolyaBot
