resolver:
  lts-20.19

packages:
- .

extra-deps:
- calamity-0.3.0.0
- di-polysemy-0.1.4.0
- data-default-0.7.0
- data-flags-0.0.3.4
- polysemy-plugin-0.4.0.0

nix:
 enable: true
 shell-file: shell.nix
