resolver:
  lts-20.11

packages:
- .

extra-deps:
- calamity-0.8.0.0
- calamity-commands-0.4.0.0
- typerep-map-0.6.0.0
- di-polysemy-0.2.0.0
- data-default-0.7.0
- data-flags-0.0.3.4
- polysemy-plugin-0.4.5.0

nix:
 enable: true
 shell-file: shell.nix
